branch-defaults:
  develop:
    environment: server-staging-backend-env
  master:
    environment: server-backend-env
global:
  application_name: server-backend
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-central-1
  include_git_submodules: true
  sc: git
  workspace_type: Application
